//! The inner door's route table, read from a FILE (R870-T18) — the config
//! surface that turns [`crate::path_route`]'s mechanism into a runnable
//! process.
//!
//! [`crate::path_route`] answers "which upstream set serves this PATH". This
//! module answers the question one layer out: **what does the inner door read
//! at startup** to learn that table. Nothing else in this crate can construct
//! a [`crate::path_route::PathRouter`] from configuration; `main.rs` calls
//! [`load`] and that is the whole surface.
//!
//! ## A file, not an env var
//!
//! `PASSWAY_UPSTREAMS`'s comma-separated grammar carries one scalar per
//! hostname. A mount carries an upstream *set* AND a response-header map, so
//! an env var would need two nesting levels invented inside one string. The
//! established idiom in this crate for a route table that carries more than a
//! scalar is a file the process re-reads (`/etc/passway-demux.routes`,
//! `/etc/passway-http-router.routes`), and this follows it.
//!
//! ## JSON, not TOML — a deliberate departure, R870-T18's format call
//!
//! R870-F15 named a TOML file as the leading candidate, on the reasoning that
//! yah's own configs (`service.toml`, `.yah/domains/<zone>.toml`) are TOML.
//! That is a property of the *producer*, and the producer is not what pays for
//! it. Three reasons the consumer's encoding is JSON instead:
//!
//! 1. **Zero new dependencies in a trust-boundary crate.** `toml` appears
//!    nowhere in this workspace's `Cargo.lock` (checked, not assumed), so
//!    reading TOML here means adding a config-language parser and its
//!    transitive graph to a public-facing listener whose manifest justifies
//!    every dependency by name. `serde_json` is already a direct dependency.
//! 2. **This is the encoding the seam already speaks.** passway already
//!    consumes control-plane output from yah as JSON —
//!    [`crate::discovery`] parses yubaba's `/service-records`. The mount
//!    table is the same kind of artifact arriving by a slower path.
//! 3. **The demux-routes precedent is about *file vs env var*, and about
//!    being hand-maintained.** Both of those files are headed "hand-maintained
//!    until X takes over"; the file half applies here and is honoured, the
//!    hand-maintained half does not — this table is generated by the
//!    `service.toml` + domain-manifest join from its first day and has no
//!    interim hand-authored phase.
//!
//! Nothing about the *shape* below is JSON-specific: it is a serde struct, so
//! if a later consumer makes hand-authoring the dominant use, the encoding is
//! a one-call change and the schema survives it.
//!
//! ## `schema_version`, which is not a compatibility shim
//!
//! The producer (yah's control plane) and the consumer (this binary) are
//! separately released and a rolling upgrade genuinely sees two versions at
//! once — the one case `CLAUDE.md`'s "below v1.0.0" rule tells you to
//! sequence for. So the version is *required* and anything but
//! [`SCHEMA_VERSION`] is a boot failure naming both numbers. It buys a loud
//! failure, never a fallback path: there is exactly one supported shape at a
//! time and no code here reads an older one.
//!
//! ## What this module does NOT validate
//!
//! Mount well-formedness, duplicate mounts and precedence are
//! [`crate::path_route::PathRouter::new`]'s job and are not re-implemented
//! here — a second validator that disagrees with the first is the same
//! divergent-normalizer trap [`crate::path`] exists to avoid, moved to the
//! config boundary. This module rejects only what the router cannot see: a
//! wrong `schema_version`, an empty table, and a mount with no upstreams.
//!
//! ## A mount can follow its workload (R936-B12)
//!
//! A mount names its backends one of two ways, never both:
//!
//! - `upstreams` — fixed addresses, for a unit pinned to where it runs.
//! - `discover` — `{ "ident": ..., "yubaba": [urls] }`: the mount polls every
//!   listed yubaba's `/service-records` for that ident, exactly as a host-routed
//!   door does ([`crate::discovery::YubabaUpstreams`]), and unions the answers.
//!   This is what lets an inner door survive its units moving: a floater that
//!   the cluster re-homes shows up in the new node's records and the mount
//!   follows it on the next poll. A fixed address baked into this file at
//!   deploy time points at the dead node forever, which is how noisetable.com
//!   went 503 on all three doors when us-east-001 went off (R936-B1).
//!
//! The discovery URLs live in the file, not in `PASSWAY_YUBABA_URL`, because a
//! path-routed door refuses the host-routing variables outright. The one env
//! var it shares is `PASSWAY_DISCOVERY_CACHE` (a directory), which gives each
//! discovering mount a last-known-good cache across restarts, keyed by ident.

use std::collections::BTreeMap;
use std::net::SocketAddr;
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;

use serde::Deserialize;

use crate::discovery::{YubabaDiscoveryConfig, YubabaUpstreams};
use crate::path_route::MountSource;
use crate::upstream::{StaticUpstreams, UpstreamSource};

/// How long one discovering mount waits on one yubaba. Same default a
/// host-routed door uses (`PASSWAY_YUBABA_TIMEOUT_SECS`).
const DISCOVER_TIMEOUT: Duration = Duration::from_secs(5);

/// How old a discovering mount's on-disk cache may be before a restart refuses
/// to seed from it. Same default as `PASSWAY_DISCOVERY_CACHE_MAX_AGE_SECS`.
const DISCOVER_CACHE_MAX_AGE: Duration = Duration::from_secs(300);

/// Environment variable naming the route-table file. Set = this process is a
/// path-routed inner door; unset = the host-routed grammars decide, exactly as
/// before R870-T18.
pub const ROUTES_FILE_ENV: &str = "PASSWAY_PATH_ROUTES_FILE";

/// The only `schema_version` this binary reads. See the module doc for why a
/// mismatch is a boot failure rather than a fallback.
pub const SCHEMA_VERSION: u32 = 1;

/// Why a route table was refused. One error type for read + parse +
/// validation, because every one of them is the same operator-facing event:
/// this door cannot start.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PathRoutesError(pub String);

impl std::fmt::Display for PathRoutesError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for PathRoutesError {}

/// The file as written by the config generator.
///
/// ```json
/// {
///   "schema_version": 1,
///   "routes": [
///     { "mount": "", "upstreams": ["127.0.0.1:8081"] },
///     { "mount": "/app", "upstreams": ["127.0.0.1:8082"],
///       "headers": { "cross-origin-opener-policy": "same-origin" } }
///   ]
/// }
/// ```
///
/// `deny_unknown_fields` on purpose: producer and consumer are separately
/// released, so a field this binary does not understand means the two have
/// drifted — and a drifted *routing* table must fail at boot, not serve
/// half of what was intended.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PathRoutesFile {
    pub schema_version: u32,
    #[serde(default)]
    pub routes: Vec<PathRouteEntry>,
}

/// One mount in the file. Mirrors [`MountSource`] minus the parts that only
/// exist once a load balancer does.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PathRouteEntry {
    /// `""` is the service root / catch-all; otherwise `/segment[/segment…]`.
    /// Validated by [`crate::path_route::PathRouter::new`], not here.
    pub mount: String,
    /// Fixed addresses serving this mount, round-robined and health-checked
    /// exactly like a host-routed set's. A mount names these OR `discover`,
    /// exactly one of the two — a mount with neither is a generator bug that
    /// would present as an unexplained 503.
    #[serde(default)]
    pub upstreams: Vec<String>,
    /// Find this mount's backends from yubaba's service records instead of a
    /// fixed list (R936-B12). See the module doc.
    #[serde(default)]
    pub discover: Option<MountDiscovery>,
    /// Response headers this mount earns, e.g. the domain manifest's
    /// COOP/COEP pair. Applied only to responses this mount served (see
    /// `PassProxy::response_filter`).
    #[serde(default)]
    pub headers: BTreeMap<String, String>,
}

impl PathRoutesFile {
    /// Parse and validate the table's bytes. Split from [`load`] so the whole
    /// grammar is testable without a filesystem.
    pub fn parse(src: &str) -> Result<Self, PathRoutesError> {
        let file: PathRoutesFile = serde_json::from_str(src)
            .map_err(|e| PathRoutesError(format!("not a valid path-routes file: {e}")))?;
        if file.schema_version != SCHEMA_VERSION {
            return Err(PathRoutesError(format!(
                "unsupported schema_version {}: this passway reads version {SCHEMA_VERSION} only. \
                 The generator that wrote this table and this binary are separately released — \
                 roll one of them, do not hand-edit the version",
                file.schema_version
            )));
        }
        if file.routes.is_empty() {
            return Err(PathRoutesError(
                "names no route: a path-routed door with an empty table 503s every request, \
                 which is indistinguishable from an outage. Declare at least a root (\"\") mount"
                    .to_string(),
            ));
        }
        for route in &file.routes {
            match (&route.discover, route.upstreams.is_empty()) {
                (None, true) => {
                    return Err(PathRoutesError(format!(
                        "mount {:?} names no upstream and no discover — a mount with no \
                         backend can only 503, and silently",
                        route.mount
                    )))
                }
                (Some(_), false) => {
                    return Err(PathRoutesError(format!(
                        "mount {:?} names both upstreams and discover — one mount has one \
                         source of backends; a fixed list beside discovery would keep \
                         routing to an address the workload left",
                        route.mount
                    )))
                }
                (Some(d), true) if d.ident.trim().is_empty() || d.yubaba.is_empty() => {
                    return Err(PathRoutesError(format!(
                        "mount {:?}: discover needs a non-empty ident and at least one yubaba \
                         URL to poll",
                        route.mount
                    )))
                }
                _ => {}
            }
        }
        Ok(file)
    }

    /// Resolve every entry's backends and hand back
    /// [`crate::path_route::build_path_router`]'s input. `cache_dir` is
    /// `PASSWAY_DISCOVERY_CACHE`: where a discovering mount keeps its
    /// last-known-good set across restarts (`None` = no cache).
    ///
    /// Address parse failures are refused rather than skipped: a table that
    /// half-loads routes some paths to the right place and the rest to a 503,
    /// which is the shape of outage nobody attributes to a typo.
    pub fn into_mount_sources(
        self,
        cache_dir: Option<&Path>,
    ) -> Result<Vec<MountSource>, PathRoutesError> {
        self.routes
            .into_iter()
            .map(|route| {
                if let Some(d) = route.discover {
                    let config = YubabaDiscoveryConfig {
                        base_urls: d.yubaba,
                        cache_path: cache_dir.map(|dir| dir.join(format!("mount-{}.json", cache_stem(&d.ident)))),
                        ident: d.ident,
                        timeout: DISCOVER_TIMEOUT,
                        cache_max_age: DISCOVER_CACHE_MAX_AGE,
                    };
                    log::info!(
                        "inner-door mount {:?}: discovering ident {:?} from {:?}",
                        route.mount,
                        config.ident,
                        config.urls()
                    );
                    return Ok(MountSource::new(
                        route.mount,
                        Arc::new(YubabaUpstreams::new(&config)) as Arc<dyn UpstreamSource>,
                    )
                    .with_headers(route.headers.into_iter().collect()));
                }
                let addrs = route
                    .upstreams
                    .iter()
                    .map(|raw| {
                        raw.parse::<SocketAddr>().map_err(|e| {
                            PathRoutesError(format!(
                                "mount {:?}: upstream {raw:?} is not an address: {e}",
                                route.mount
                            ))
                        })
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(MountSource::new(
                    route.mount,
                    Arc::new(StaticUpstreams::new(addrs)) as Arc<dyn UpstreamSource>,
                )
                .with_headers(route.headers.into_iter().collect()))
            })
            .collect()
    }
}

/// Read `path` and turn it into [`crate::path_route::build_path_router`]'s
/// input. The whole config surface — see this module's doc.
pub fn load(path: &Path) -> Result<Vec<MountSource>, PathRoutesError> {
    let src = std::fs::read_to_string(path).map_err(|e| {
        PathRoutesError(format!(
            "reading {} ({ROUTES_FILE_ENV}): {e}",
            path.display()
        ))
    })?;
    let cache_dir = std::env::var("PASSWAY_DISCOVERY_CACHE")
        .ok()
        .filter(|d| !d.trim().is_empty())
        .map(std::path::PathBuf::from);
    PathRoutesFile::parse(&src)
        .map_err(|e| PathRoutesError(format!("{} ({ROUTES_FILE_ENV}) {e}", path.display())))?
        .into_mount_sources(cache_dir.as_deref())
}

/// A mount's discovery source: which workload, and which yubabas to ask.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MountDiscovery {
    /// The workload's mesh ident, as it appears in `/service-records`.
    pub ident: String,
    /// Base URLs (`http://<mesh-ip>:7443`) of every node the workload may run
    /// on. List them all: a floater is only found where it is polled for.
    pub yubaba: Vec<String>,
}

/// Idents are config, so the cache file name is sanitized rather than trusted.
fn cache_stem(ident: &str) -> String {
    ident
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '.' { c } else { '_' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::path_route::build_path_router;
    use std::time::Duration;

    const TWO_MOUNTS: &str = r#"{
        "schema_version": 1,
        "routes": [
            { "mount": "", "upstreams": ["127.0.0.1:8081"] },
            { "mount": "/app", "upstreams": ["127.0.0.1:8082", "127.0.0.1:8083"],
              "headers": {
                  "cross-origin-opener-policy": "same-origin",
                  "cross-origin-embedder-policy": "require-corp"
              } }
        ]
    }"#;

    #[test]
    fn a_two_mount_table_parses_into_mount_sources() {
        let sources = PathRoutesFile::parse(TWO_MOUNTS)
            .expect("valid table")
            .into_mount_sources(None)
            .expect("resolvable addresses");
        assert_eq!(sources.len(), 2);
        assert_eq!(sources[0].mount, "");
        assert!(sources[0].headers.is_empty());
        assert_eq!(sources[1].mount, "/app");
        assert_eq!(
            sources[1].headers,
            vec![
                (
                    "cross-origin-embedder-policy".to_string(),
                    "require-corp".to_string()
                ),
                (
                    "cross-origin-opener-policy".to_string(),
                    "same-origin".to_string()
                ),
            ]
        );
    }

    /// The end-to-end config path this module exists for: file bytes in, a
    /// validated router out, with the mount the request will actually match.
    #[test]
    fn a_parsed_table_builds_a_router_that_resolves_its_mounts() {
        let sources = PathRoutesFile::parse(TWO_MOUNTS)
            .unwrap()
            .into_mount_sources(None)
            .unwrap();
        let (router, _services) = build_path_router(
            sources,
            Duration::from_millis(100),
            Duration::from_millis(100),
        )
        .expect("valid mount table");
        assert_eq!(router.resolve("/app/settings").map(|r| r.mount.as_str()), Some("/app"));
        // The segment-safety rule the mechanism owns, reached through the
        // config surface rather than through a hand-built router.
        assert_eq!(router.resolve("/application").map(|r| r.mount.as_str()), Some(""));
    }

    #[test]
    fn a_wrong_schema_version_is_refused_and_names_both_numbers() {
        let err = PathRoutesFile::parse(r#"{"schema_version": 2, "routes": []}"#).unwrap_err();
        assert!(err.to_string().contains("unsupported schema_version 2"), "{err}");
        assert!(err.to_string().contains("version 1 only"), "{err}");
    }

    #[test]
    fn an_empty_table_is_refused_rather_than_503ing_every_request() {
        let err = PathRoutesFile::parse(r#"{"schema_version": 1, "routes": []}"#).unwrap_err();
        assert!(err.to_string().contains("names no route"), "{err}");
    }

    #[test]
    fn a_discover_mount_must_stand_alone_and_be_complete() {
        let both = r#"{"schema_version": 1, "routes": [{"mount": "", "upstreams": ["127.0.0.1:1"],
            "discover": {"ident": "x", "yubaba": ["http://127.0.0.1:7443"]}}]}"#;
        let err = PathRoutesFile::parse(both).unwrap_err();
        assert!(err.to_string().contains("both upstreams and discover"), "{err}");

        let no_urls = r#"{"schema_version": 1, "routes": [{"mount": "",
            "discover": {"ident": "x", "yubaba": []}}]}"#;
        let err = PathRoutesFile::parse(no_urls).unwrap_err();
        assert!(err.to_string().contains("at least one yubaba"), "{err}");

        let typo = r#"{"schema_version": 1, "routes": [{"mount": "",
            "discover": {"ident": "x", "yubabas": ["http://127.0.0.1:7443"]}}]}"#;
        assert!(PathRoutesFile::parse(typo).is_err(), "a misspelled discover key must not boot");
    }

    /// One tiny HTTP responder answering every request with `body`.
    async fn serve(body: &'static str) -> String {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        tokio::spawn(async move {
            while let Ok((mut stream, _)) = listener.accept().await {
                let mut buf = [0u8; 1024];
                let _ = stream.read(&mut buf).await;
                let resp = format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\n\
                     content-length: {}\r\nconnection: close\r\n\r\n{body}",
                    body.len()
                );
                let _ = stream.write_all(resp.as_bytes()).await;
                let _ = stream.shutdown().await;
            }
        });
        format!("http://{addr}")
    }

    /// R936-B12: a discovering mount finds its unit on whichever listed node
    /// runs it — here the second of two — and takes only that ident's
    /// records, so it follows a floater the cluster re-homed.
    #[tokio::test]
    async fn a_discover_mount_follows_its_ident_across_every_listed_yubaba() {
        let empty_node = serve(r#"{"version":1,"records":[
            {"ident":"noisetable","endpoints":["100.64.0.2:41000"],"health":"ready",
             "mesh_ip":"100.64.0.2","ports":[41000],"container_id":"c","observed_at_unix_ms":1}
        ]}"#)
        .await;
        let owner_node = serve(r#"{"version":1,"records":[
            {"ident":"noisetable-marketing-issues","endpoints":["100.64.0.1:4333"],"health":"ready",
             "mesh_ip":"100.64.0.1","ports":[4333],"container_id":"c","observed_at_unix_ms":1}
        ]}"#)
        .await;
        let table = format!(
            r#"{{"schema_version": 1, "routes": [
                {{"mount": "", "upstreams": ["127.0.0.1:8081"]}},
                {{"mount": "/api/issues", "discover": {{"ident": "noisetable-marketing-issues",
                  "yubaba": ["{empty_node}", "{owner_node}"]}}}}
            ]}}"#
        );
        let sources = PathRoutesFile::parse(&table)
            .unwrap()
            .into_mount_sources(None)
            .unwrap();
        let issues = sources.iter().find(|s| s.mount == "/api/issues").unwrap();
        assert_eq!(
            issues.source.addrs().await,
            vec!["100.64.0.1:4333".parse::<SocketAddr>().unwrap()]
        );
    }

    #[test]
    fn a_mount_with_no_upstream_is_refused() {
        let err = PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [{"mount": "/app", "upstreams": []}]}"#,
        )
        .unwrap_err();
        assert!(err.to_string().contains("names no upstream"), "{err}");
    }

    /// Producer/consumer drift must be loud: a field this binary does not
    /// understand means the two have moved apart, and a half-understood
    /// routing table is worse than no door.
    #[test]
    fn an_unknown_field_is_refused_rather_than_ignored() {
        let err = PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [
                 {"mount": "", "upstreams": ["127.0.0.1:1"], "tls": true}]}"#,
        )
        .unwrap_err();
        assert!(err.to_string().contains("unknown field"), "{err}");
    }

    #[test]
    fn a_malformed_address_refuses_the_whole_table_rather_than_half_loading() {
        // `MountSource` holds an `Arc<dyn UpstreamSource>` and no `Debug`, so
        // the Ok side can't be unwrapped away — match it out.
        let err = match PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [
                 {"mount": "", "upstreams": ["127.0.0.1:8081"]},
                 {"mount": "/app", "upstreams": ["not-an-address"]}]}"#,
        )
        .unwrap()
        .into_mount_sources(None)
        {
            Ok(_) => panic!("a malformed address must refuse the table"),
            Err(e) => e,
        };
        assert!(err.to_string().contains("not-an-address"), "{err}");
        assert!(err.to_string().contains("\"/app\""), "{err}");
    }

    /// A malformed *mount* is the router's call, not this module's — proof
    /// that the single validator is reached through the config path.
    #[test]
    fn mount_validation_is_left_to_the_router_and_still_fires() {
        let sources = PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [
                 {"mount": "app/", "upstreams": ["127.0.0.1:8081"]}]}"#,
        )
        .unwrap()
        .into_mount_sources(None)
        .unwrap();
        let err = match build_path_router(
            sources,
            Duration::from_millis(100),
            Duration::from_millis(100),
        ) {
            Ok(_) => panic!("a mount with no leading slash and a trailing slash is invalid"),
            Err(e) => e,
        };
        assert!(err.to_string().contains("invalid mount"), "{err}");
    }
}
