//! The inner door's route table, read from a FILE (R870-T18) — the config
//! surface that turns [`crate::path_route`]'s mechanism into a runnable
//! process.
//!
//! [`crate::path_route`] answers "which upstream set serves this PATH". This
//! module answers the question one layer out: **what does the inner door read
//! at startup** to learn that table. Nothing else in this crate can construct
//! a [`crate::path_route::PathRouter`] from configuration; `main.rs` calls
//! [`load`] and that is the whole surface.
//!
//! ## A file, not an env var
//!
//! `PASSWAY_UPSTREAMS`'s comma-separated grammar carries one scalar per
//! hostname. A mount carries an upstream *set* AND a response-header map, so
//! an env var would need two nesting levels invented inside one string. The
//! established idiom in this crate for a route table that carries more than a
//! scalar is a file the process re-reads (`/etc/passway-demux.routes`,
//! `/etc/passway-http-router.routes`), and this follows it.
//!
//! ## JSON, not TOML — a deliberate departure, R870-T18's format call
//!
//! R870-F15 named a TOML file as the leading candidate, on the reasoning that
//! yah's own configs (`service.toml`, `.yah/domains/<zone>.toml`) are TOML.
//! That is a property of the *producer*, and the producer is not what pays for
//! it. Three reasons the consumer's encoding is JSON instead:
//!
//! 1. **Zero new dependencies in a trust-boundary crate.** `toml` appears
//!    nowhere in this workspace's `Cargo.lock` (checked, not assumed), so
//!    reading TOML here means adding a config-language parser and its
//!    transitive graph to a public-facing listener whose manifest justifies
//!    every dependency by name. `serde_json` is already a direct dependency.
//! 2. **This is the encoding the seam already speaks.** passway already
//!    consumes control-plane output from yah as JSON —
//!    [`crate::discovery`] parses yubaba's `/service-records`. The mount
//!    table is the same kind of artifact arriving by a slower path.
//! 3. **The demux-routes precedent is about *file vs env var*, and about
//!    being hand-maintained.** Both of those files are headed "hand-maintained
//!    until X takes over"; the file half applies here and is honoured, the
//!    hand-maintained half does not — this table is generated by the
//!    `service.toml` + domain-manifest join from its first day and has no
//!    interim hand-authored phase.
//!
//! Nothing about the *shape* below is JSON-specific: it is a serde struct, so
//! if a later consumer makes hand-authoring the dominant use, the encoding is
//! a one-call change and the schema survives it.
//!
//! ## `schema_version`, which is not a compatibility shim
//!
//! The producer (yah's control plane) and the consumer (this binary) are
//! separately released and a rolling upgrade genuinely sees two versions at
//! once — the one case `CLAUDE.md`'s "below v1.0.0" rule tells you to
//! sequence for. So the version is *required* and anything but
//! [`SCHEMA_VERSION`] is a boot failure naming both numbers. It buys a loud
//! failure, never a fallback path: there is exactly one supported shape at a
//! time and no code here reads an older one.
//!
//! ## What this module does NOT validate
//!
//! Mount well-formedness, duplicate mounts and precedence are
//! [`crate::path_route::PathRouter::new`]'s job and are not re-implemented
//! here — a second validator that disagrees with the first is the same
//! divergent-normalizer trap [`crate::path`] exists to avoid, moved to the
//! config boundary. This module rejects only what the router cannot see: a
//! wrong `schema_version`, an empty table, and a mount with no upstreams.

use std::collections::BTreeMap;
use std::net::SocketAddr;
use std::path::Path;
use std::sync::Arc;

use serde::Deserialize;

use crate::path_route::MountSource;
use crate::upstream::{StaticUpstreams, UpstreamSource};

/// Environment variable naming the route-table file. Set = this process is a
/// path-routed inner door; unset = the host-routed grammars decide, exactly as
/// before R870-T18.
pub const ROUTES_FILE_ENV: &str = "PASSWAY_PATH_ROUTES_FILE";

/// The only `schema_version` this binary reads. See the module doc for why a
/// mismatch is a boot failure rather than a fallback.
pub const SCHEMA_VERSION: u32 = 1;

/// Why a route table was refused. One error type for read + parse +
/// validation, because every one of them is the same operator-facing event:
/// this door cannot start.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PathRoutesError(pub String);

impl std::fmt::Display for PathRoutesError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for PathRoutesError {}

/// The file as written by the config generator.
///
/// ```json
/// {
///   "schema_version": 1,
///   "routes": [
///     { "mount": "", "upstreams": ["127.0.0.1:8081"] },
///     { "mount": "/app", "upstreams": ["127.0.0.1:8082"],
///       "headers": { "cross-origin-opener-policy": "same-origin" } }
///   ]
/// }
/// ```
///
/// `deny_unknown_fields` on purpose: producer and consumer are separately
/// released, so a field this binary does not understand means the two have
/// drifted — and a drifted *routing* table must fail at boot, not serve
/// half of what was intended.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PathRoutesFile {
    pub schema_version: u32,
    #[serde(default)]
    pub routes: Vec<PathRouteEntry>,
}

/// One mount in the file. Mirrors [`MountSource`] minus the parts that only
/// exist once a load balancer does.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PathRouteEntry {
    /// `""` is the service root / catch-all; otherwise `/segment[/segment…]`.
    /// Validated by [`crate::path_route::PathRouter::new`], not here.
    pub mount: String,
    /// Addresses serving this mount, round-robined and health-checked exactly
    /// like a host-routed set's. Must be non-empty — a mount with no upstream
    /// is a generator bug that would present as an unexplained 503.
    pub upstreams: Vec<String>,
    /// Response headers this mount earns, e.g. the domain manifest's
    /// COOP/COEP pair. Applied only to responses this mount served (see
    /// `PassProxy::response_filter`).
    #[serde(default)]
    pub headers: BTreeMap<String, String>,
}

impl PathRoutesFile {
    /// Parse and validate the table's bytes. Split from [`load`] so the whole
    /// grammar is testable without a filesystem.
    pub fn parse(src: &str) -> Result<Self, PathRoutesError> {
        let file: PathRoutesFile = serde_json::from_str(src)
            .map_err(|e| PathRoutesError(format!("not a valid path-routes file: {e}")))?;
        if file.schema_version != SCHEMA_VERSION {
            return Err(PathRoutesError(format!(
                "unsupported schema_version {}: this passway reads version {SCHEMA_VERSION} only. \
                 The generator that wrote this table and this binary are separately released — \
                 roll one of them, do not hand-edit the version",
                file.schema_version
            )));
        }
        if file.routes.is_empty() {
            return Err(PathRoutesError(
                "names no route: a path-routed door with an empty table 503s every request, \
                 which is indistinguishable from an outage. Declare at least a root (\"\") mount"
                    .to_string(),
            ));
        }
        for route in &file.routes {
            if route.upstreams.is_empty() {
                return Err(PathRoutesError(format!(
                    "mount {:?} names no upstream — a mount with no backend can only 503, \
                     and silently",
                    route.mount
                )));
            }
        }
        Ok(file)
    }

    /// Resolve every entry's addresses and hand back
    /// [`crate::path_route::build_path_router`]'s input.
    ///
    /// Address parse failures are refused rather than skipped: a table that
    /// half-loads routes some paths to the right place and the rest to a 503,
    /// which is the shape of outage nobody attributes to a typo.
    pub fn into_mount_sources(self) -> Result<Vec<MountSource>, PathRoutesError> {
        self.routes
            .into_iter()
            .map(|route| {
                let addrs = route
                    .upstreams
                    .iter()
                    .map(|raw| {
                        raw.parse::<SocketAddr>().map_err(|e| {
                            PathRoutesError(format!(
                                "mount {:?}: upstream {raw:?} is not an address: {e}",
                                route.mount
                            ))
                        })
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(MountSource::new(
                    route.mount,
                    Arc::new(StaticUpstreams::new(addrs)) as Arc<dyn UpstreamSource>,
                )
                .with_headers(route.headers.into_iter().collect()))
            })
            .collect()
    }
}

/// Read `path` and turn it into [`crate::path_route::build_path_router`]'s
/// input. The whole config surface — see this module's doc.
pub fn load(path: &Path) -> Result<Vec<MountSource>, PathRoutesError> {
    let src = std::fs::read_to_string(path).map_err(|e| {
        PathRoutesError(format!(
            "reading {} ({ROUTES_FILE_ENV}): {e}",
            path.display()
        ))
    })?;
    PathRoutesFile::parse(&src)
        .map_err(|e| PathRoutesError(format!("{} ({ROUTES_FILE_ENV}) {e}", path.display())))?
        .into_mount_sources()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::path_route::build_path_router;
    use std::time::Duration;

    const TWO_MOUNTS: &str = r#"{
        "schema_version": 1,
        "routes": [
            { "mount": "", "upstreams": ["127.0.0.1:8081"] },
            { "mount": "/app", "upstreams": ["127.0.0.1:8082", "127.0.0.1:8083"],
              "headers": {
                  "cross-origin-opener-policy": "same-origin",
                  "cross-origin-embedder-policy": "require-corp"
              } }
        ]
    }"#;

    #[test]
    fn a_two_mount_table_parses_into_mount_sources() {
        let sources = PathRoutesFile::parse(TWO_MOUNTS)
            .expect("valid table")
            .into_mount_sources()
            .expect("resolvable addresses");
        assert_eq!(sources.len(), 2);
        assert_eq!(sources[0].mount, "");
        assert!(sources[0].headers.is_empty());
        assert_eq!(sources[1].mount, "/app");
        assert_eq!(
            sources[1].headers,
            vec![
                (
                    "cross-origin-embedder-policy".to_string(),
                    "require-corp".to_string()
                ),
                (
                    "cross-origin-opener-policy".to_string(),
                    "same-origin".to_string()
                ),
            ]
        );
    }

    /// The end-to-end config path this module exists for: file bytes in, a
    /// validated router out, with the mount the request will actually match.
    #[test]
    fn a_parsed_table_builds_a_router_that_resolves_its_mounts() {
        let sources = PathRoutesFile::parse(TWO_MOUNTS)
            .unwrap()
            .into_mount_sources()
            .unwrap();
        let (router, _services) = build_path_router(
            sources,
            Duration::from_millis(100),
            Duration::from_millis(100),
        )
        .expect("valid mount table");
        assert_eq!(router.resolve("/app/settings").map(|r| r.mount.as_str()), Some("/app"));
        // The segment-safety rule the mechanism owns, reached through the
        // config surface rather than through a hand-built router.
        assert_eq!(router.resolve("/application").map(|r| r.mount.as_str()), Some(""));
    }

    #[test]
    fn a_wrong_schema_version_is_refused_and_names_both_numbers() {
        let err = PathRoutesFile::parse(r#"{"schema_version": 2, "routes": []}"#).unwrap_err();
        assert!(err.to_string().contains("unsupported schema_version 2"), "{err}");
        assert!(err.to_string().contains("version 1 only"), "{err}");
    }

    #[test]
    fn an_empty_table_is_refused_rather_than_503ing_every_request() {
        let err = PathRoutesFile::parse(r#"{"schema_version": 1, "routes": []}"#).unwrap_err();
        assert!(err.to_string().contains("names no route"), "{err}");
    }

    #[test]
    fn a_mount_with_no_upstream_is_refused() {
        let err = PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [{"mount": "/app", "upstreams": []}]}"#,
        )
        .unwrap_err();
        assert!(err.to_string().contains("names no upstream"), "{err}");
    }

    /// Producer/consumer drift must be loud: a field this binary does not
    /// understand means the two have moved apart, and a half-understood
    /// routing table is worse than no door.
    #[test]
    fn an_unknown_field_is_refused_rather_than_ignored() {
        let err = PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [
                 {"mount": "", "upstreams": ["127.0.0.1:1"], "tls": true}]}"#,
        )
        .unwrap_err();
        assert!(err.to_string().contains("unknown field"), "{err}");
    }

    #[test]
    fn a_malformed_address_refuses_the_whole_table_rather_than_half_loading() {
        // `MountSource` holds an `Arc<dyn UpstreamSource>` and no `Debug`, so
        // the Ok side can't be unwrapped away — match it out.
        let err = match PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [
                 {"mount": "", "upstreams": ["127.0.0.1:8081"]},
                 {"mount": "/app", "upstreams": ["not-an-address"]}]}"#,
        )
        .unwrap()
        .into_mount_sources()
        {
            Ok(_) => panic!("a malformed address must refuse the table"),
            Err(e) => e,
        };
        assert!(err.to_string().contains("not-an-address"), "{err}");
        assert!(err.to_string().contains("\"/app\""), "{err}");
    }

    /// A malformed *mount* is the router's call, not this module's — proof
    /// that the single validator is reached through the config path.
    #[test]
    fn mount_validation_is_left_to_the_router_and_still_fires() {
        let sources = PathRoutesFile::parse(
            r#"{"schema_version": 1, "routes": [
                 {"mount": "app/", "upstreams": ["127.0.0.1:8081"]}]}"#,
        )
        .unwrap()
        .into_mount_sources()
        .unwrap();
        let err = match build_path_router(
            sources,
            Duration::from_millis(100),
            Duration::from_millis(100),
        ) {
            Ok(_) => panic!("a mount with no leading slash and a trailing slash is invalid"),
            Err(e) => e,
        };
        assert!(err.to_string().contains("invalid mount"), "{err}");
    }
}
